#! /bin/sh

# Swap caps lock with ctrl
xmodmap ~/.Xmodmap &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc rule -a Zathura state=tiled follow=on

bspc config focused_border_color "#f7768e"
bspc config normal_border_color "#11121d"
bspc config presel_feedback_color "#f7768e"

bspc config focus_follows_pointer false
